import type { Metadata } from 'next';
import './globals.css';
import Navbar from './layouts/navbar/home-navbar';
import Footer from './layouts/footer/home-footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en ">
      <body className={`flex flex-col justify-between bg-brown-50 antialiased min-h-screen `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
