import type { Metadata } from 'next';
import './globals.css';
import Navbar from './layouts/navbar/home-navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-brown-50 antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
